version: "3"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana

  api:
    build: .
    container_name: resume-insight
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    depends_on:
      - loki
    restart: "no"
volumes:
  grafana_data:
